services:
  nutrimenu-api:
    build: 
      context: ./nutrimenu-api
      dockerfile: Dockerfile
    container_name: nutrimenu-api
    restart: always
    ports:
      - "8000:80"
    command: 
      - uvicorn
      - main:app
      - --port
      - "80"
      - --host
      - "0.0.0.0"
      - --reload
    volumes:
      - ./nutrimenu-api:/nutrimenu
    env_file:
      - ./nutrimenu-api/.env
